from abc import ABC, abstractmethod


class IResidentsService(ABC):
    """
    ResidentsService interface with residents methods
    """

    @abstractmethod
    def to_json_list(self, residents_results):
        """
        Turns the residents_results from the sql query into json format
        :param residents_results: residents retrieved from resident table
        :type id: objects from resident table
        """

        pass

    @abstractmethod
    def add_resident(self, id, initial, room_num, date_joined, date_left, building):
        """
        Add a resident to the database
        :param id: autogenerated unique id of the resident
        :type id: int
        :param initial: initial of resident
        :type initial: string
        :param room_num: room number which the resident resides in
        :type room_num: integer
        :param date_joined: the date the resident joined
        :type date_joined: date
        :param date_left: the date the resident left, if exists
        :type date_left: date
        :param building: the building in which the resident is staying
        :type building: Enum("144", "402", "362)
        :raises Exception: if resident creation fails
        """
        pass

    @abstractmethod
    def update_resident(self, resident_id, updated_resident):
        """
        Update a resident
        :param resident_id: resident id of resudent to be updated
        :type log_id: int
        :param updated_resident: json object from the request of the updated resident record
        :type updated_resident: json object
        :raises Exception: if resident retrieval fails
        """
        pass

    @abstractmethod
    def delete_resident(self, resident_id):
        """
        Delete a resident
        :param resident_id: id of resident to be deleted
        :type resident_id: int
        :raises Exception: if resident retrieval fails
        """
        pass

    @abstractmethod
    def get_resident(self, resident_id, id):
        """
        Gets residents in json format.
        :param resident_id: id of resident to be deleted in the format of initial+room_num
        :type resident_id: string
        :param id: id of resident to be deleted, the primary key of the resident
        :type resident_id: initial
        """
        pass
