"""adding db table for logging user data

Revision ID: f97592e183de
Revises: 797bfedc3a06
Create Date: 2023-02-05 19:50:41.833067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f97592e183de"
down_revision = "797bfedc3a06"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sign_in_log",
        sa.Column("log_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("time", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("log_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sign_in_log")
    # ### end Alembic commands ###
