"""update resident table

Revision ID: 1d0a6e20fcf8
Revises: a5d22b31faab
Create Date: 2023-05-30 01:14:48.744831

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1d0a6e20fcf8'
down_revision = 'a5d22b31faab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log_records', schema=None) as batch_op:
        batch_op.alter_column('note',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_constraint('log_records_resident_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('log_records_employee_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['employee_id'], ['id'])
        batch_op.create_foreign_key(None, 'residents', ['resident_id'], ['id'])

    with op.batch_alter_table('residents', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('residents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', postgresql.ENUM('Current', 'Past', name='statuses'), autoincrement=False, nullable=False))

    with op.batch_alter_table('log_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('log_records_employee_id_fkey', 'residents', ['employee_id'], ['id'])
        batch_op.create_foreign_key('log_records_resident_id_fkey', 'users', ['resident_id'], ['id'])
        batch_op.alter_column('note',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
