"""update_resident_date_fields

Revision ID: 24fad25f60e3
Revises: a5d22b31faab
Create Date: 2023-09-26 19:33:15.491168

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "24fad25f60e3"
down_revision = "a5d22b31faab"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("residents", schema=None) as batch_op:
        batch_op.alter_column(
            "date_joined",
            existing_type=postgresql.TIMESTAMP(timezone=True),
            type_=sa.Date(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "date_left",
            existing_type=postgresql.TIMESTAMP(timezone=True),
            type_=sa.Date(),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("residents", schema=None) as batch_op:
        batch_op.alter_column(
            "date_left",
            existing_type=sa.Date(),
            type_=postgresql.TIMESTAMP(timezone=True),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "date_joined",
            existing_type=sa.Date(),
            type_=postgresql.TIMESTAMP(timezone=True),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
