"""added residence table

Revision ID: 40077f247b39
Revises: 58313513d17f
Create Date: 2023-03-12 18:58:14.051521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40077f247b39'
down_revision = '58313513d17f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('residences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_joined', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('undetermined', name='statusenum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('residences')
    # ### end Alembic commands ###
