"""create show members table

Revision ID: 401245fb6e0f
Revises: fd734d591b67
Create Date: 2023-05-07 20:54:55.429854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '401245fb6e0f'
down_revision = 'fd734d591b67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SHOW_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('PM', 'Designer', 'PL', 'Developer', name='team_roles'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SHOW_members')
    # ### end Alembic commands ###
