"""create log records attn to junction table

Revision ID: 51ad56d133e9
Revises: eff8a5a7fda3
Create Date: 2024-04-21 00:02:19.646800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "51ad56d133e9"
down_revision = "eff8a5a7fda3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "log_record_attn_tos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("log_record_id", sa.Integer(), nullable=False),
        sa.Column("attn_to_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["attn_to_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["log_record_id"],
            ["log_records.log_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("log_record_attn_tos")
    # ### end Alembic commands ###
