"""remove attn_to column from log records table

Revision ID: 5a9f9b3bdc20
Revises: 51ad56d133e9
Create Date: 2024-04-21 04:15:23.112342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5a9f9b3bdc20"
down_revision = "51ad56d133e9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("log_records", schema=None) as batch_op:
        batch_op.drop_constraint("log_records_attn_to_fkey", type_="foreignkey")
        batch_op.drop_column("attn_to")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("log_records", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("attn_to", sa.INTEGER(), autoincrement=False, nullable=True)
        )
        batch_op.create_foreign_key(
            "log_records_attn_to_fkey", "users", ["attn_to"], ["id"]
        )

    # ### end Alembic commands ###
