"""add unique constraint to combined resident id

Revision ID: 6ba7859cdf27
Revises: a1f05c8f324c
Create Date: 2024-01-29 02:25:45.352261

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "6ba7859cdf27"
down_revision = "a1f05c8f324c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("entities")
    with op.batch_alter_table("residents", schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ["initial", "room_num"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("residents", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")

    op.create_table(
        "entities",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("string_field", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("int_field", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "enum_field",
            postgresql.ENUM("A", "B", "C", "D", name="enum"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "string_array_field",
            postgresql.ARRAY(sa.VARCHAR()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("bool_field", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("file_name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="entities_pkey"),
    )
    # ### end Alembic commands ###
