"""upgrade the fields of residents table

Revision ID: 80bd1c12f8fb
Revises: 40077f247b39
Create Date: 2023-03-15 01:07:56.418497

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '80bd1c12f8fb'
down_revision = '40077f247b39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('residents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('initial', sa.String(), nullable=False),
    sa.Column('room_num', sa.Integer(), nullable=False),
    sa.Column('date_joined', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('Current', 'Past', name='statuses'), nullable=False),
    sa.Column('building', sa.Enum('Seniors', 'Adults', 'Supports', name='buildings'), nullable=False),
    sa.Column('address', sa.Enum('144 Erb St. East', '402 Erb St. West', '362 Erb St. West', name='buildings'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('residences')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('residences',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date_joined', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('undetermined', name='statusenum'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='residences_pkey')
    )
    op.drop_table('residents')
    # ### end Alembic commands ###
