"""upgrade bulding enum values

Revision ID: ab7e2e3cbea3
Revises: 80bd1c12f8fb
Create Date: 2023-03-19 01:26:29.392661

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ab7e2e3cbea3'
down_revision = '80bd1c12f8fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('residents', schema=None) as batch_op:
        batch_op.drop_column('address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('residents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', postgresql.ENUM('Seniors', 'Adults', 'Supports', name='buildings'), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
