"""change resident room number to be string

Revision ID: eff8a5a7fda3
Revises: 6ba7859cdf27
Create Date: 2024-01-31 04:13:02.272243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "eff8a5a7fda3"
down_revision = "6ba7859cdf27"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("residents", schema=None) as batch_op:
        batch_op.alter_column(
            "room_num",
            existing_type=sa.INTEGER(),
            type_=sa.String(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("residents", schema=None) as batch_op:
        batch_op.alter_column(
            "room_num",
            existing_type=sa.String(),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
