"""add date_left column

Revision ID: f33ff1dc7c5d
Revises: ab7e2e3cbea3
Create Date: 2023-03-19 18:00:34.627826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f33ff1dc7c5d'
down_revision = 'ab7e2e3cbea3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('residents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_left', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('residents', schema=None) as batch_op:
        batch_op.drop_column('date_left')

    # ### end Alembic commands ###
